name: E2E Automation Exercise Tests

on:
  workflow_dispatch: # Manual launch of workflow

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Run Playwright tests for e2e_AutomationExercise in Chromium only
      - name: Run Playwright tests
        run: npx playwright test tests/e2e_AutomationExercise --project=chromium --reporter=dot
